---
all:
  children:
    automation_controller:
      hosts:
        tower-01:
          ansible_host: 192.168.1.61
        tower-02:
          ansible_host: 192.168.1.62
    managed_linux:
      hosts:
        linux-01:
          ansible_host: 192.168.1.71
        linux-02:
          ansible_host: 192.168.1.72
        linux-03:
          ansible_host: 192.168.1.73
